### ISSUE TITLE
robot.CombineKey() is not working

### ISSUE THREAD

**Issue by manhustbk** [lucassklp/Desktop.Robot#55]
**Environment**
* I'm coding c#, open nuget packages and
*I installed Desktop.Robot version 1.5.0
```
using Desktop.Robot;
using Desktop.Robot.Extensions;

robot.CombineKey(Key.Shift, Key.QuotationMark)
```

**Issue**: 
*When i'm using robot.CombineKey(Key.Shift, Key.QuotationMark) then it not working.

**Expect** :
*it will press key "?" but it presses key Z

As i check Desktop.Robot lib then i see that keycode or QuotationMark is 90 same as keycode of Z key is 90.
So could you help me explain? key code of QuotatiinMark is 90. is right?

If the keycode of QuotatiinMark is correct, can you show me how to use the CombineKey function or some way to be able to enter the "?"

@DanDecrypted @lucassklp @susch19 @olivercoad please help me check?

**Comment by olivercoad** [comment]
Hi @manhustbk,

It looks like you're using windows as you mention the keycode 90. I've just made a PR with the fixed keycodes for quotation marks on windows.

If so, `CombineKeys` is working fine on Windows and this issue is actually about the incorrect keycodes. Can you please rename the issue so that it doesn't get confused with a different issue about `CombineKeys` on linux?

**Comment by manhustbk** [comment]
Hi @olivercoad 

I'm using on window. 
I installed Desktop.Robot version 1.5.0 by nuget from my project on Visual studio
This problem appears in the window. And some other key that have keycode = 90 is same with keycode of Z key. 

You can see in Key.cs file (0x5A same 90)
Currently:
        [Keycode(Platform = "OSX", Keycode = 0x27)]
        [Keycode(Platform = "Windows", Keycode = 0x5A)]
        [Keycode(Platform = "Linux", Keycode = 0x0022)]
        QuotationMark,
        
I'm try change Keycode = 0xBF (same 191) of QuotationMark and build project, and copy Desktop.Robot.dll then it is SUCCESSFULLY: 
        [Keycode(Platform = "OSX", Keycode = 0x27)]
        [Keycode(Platform = "Windows", Keycode = 0xBF)]
        [Keycode(Platform = "Linux", Keycode = 0x0022)]
        QuotationMark,
        
In addition, some of the following keys have the wrong keycode
Colon, Semicolon, Dot, Slash, Backslash, Percent, LessThan, Equal, GreaterThan, OpenParenthesis, CloseParenthesis, OpenBracket, CloseBracket, OpenBrace, CloseBrace, Interrogation
They all have keycode Keycode = 0x5A like keyboard Z.
Please help me check it
